# Generated by Django 5.2.17 on 2026-09-16 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('open_at', models.DateTimeField()),
                ('close_at', models.DateTimeField()),
                ('join_code', models.CharField(db_index=True, max_length=6, unique=True)),
                ('n_to_answer', models.PositiveIntegerField()),
                ('points_per_question', models.PositiveIntegerField(default=1)),
                ('seconds_objective', models.PositiveIntegerField(default=20)),
                ('seconds_subjective', models.PositiveIntegerField(default=60)),
                ('allow_review', models.BooleanField(default=False)),
                ('results_released_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['open_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mcq', 'Multiple choice'), ('tf', 'True / False'), ('short', 'Short answer')], max_length=6)),
                ('text', models.TextField()),
                ('options', models.TextField(blank=True)),
                ('answer_key', models.CharField(blank=True, max_length=10)),
                ('accepted_answers', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.test')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawn_ids', models.TextField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.test')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, max_length=10)),
                ('text', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='assessments.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_answer')],
            },
        ),
        migrations.AddConstraint(
            model_name='attempt',
            constraint=models.UniqueConstraint(fields=('test', 'student'), name='uniq_attempt_test_student'),
        ),
    ]
