# Generated by Django 5.2.17 on 2026-09-16 16:04

import assessments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='join_code',
            field=models.CharField(db_index=True, default=assessments.models.make_join_code, max_length=6, unique=True),
        ),
    ]
