# Generated by Django 5.2.17 on 2026-09-16 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='allowed_ext',
            field=models.CharField(default='pdf', max_length=100),
        ),
    ]
